WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:14客诉工单 详情
INFO     root:mylogger.py:78 case用例:14客诉工单 详情
WARNING  celery.redirected:log.py:227 [2021-06-10 15:31:14,702] | mylogger.py |INFO  : case用例:14客诉工单 详情
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderDetails
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderDetails
WARNING  celery.redirected:log.py:227 [2021-06-10 15:31:14,703] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/workOrderDetails
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：e570e051-8463-4fb1-ae78-9f484a8543a9
INFO     root:mylogger.py:78 token：e570e051-8463-4fb1-ae78-9f484a8543a9
WARNING  celery.redirected:log.py:227 [2021-06-10 15:31:14,703] | mylogger.py |INFO  : token：e570e051-8463-4fb1-ae78-9f484a8543a9
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer e570e051-8463-4fb1-ae78-9f484a8543a9', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :get
WARNING  celery.redirected:log.py:227 pararm :{"id":6}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 get 请求 ....
DEBUG    root:mylogger.py:80 get 请求 ....
WARNING  celery.redirected:log.py:227 [2021-06-10 15:31:14,704] | mylogger.py |DEBUG : get 请求 ....
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderDetails?id=6 HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderDetails?id=6 HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': 0, 'data': {'id': 6, 'type': 1, 'stationId': 100208, 'details': '测试', 'status': 1, 'createTime': '2021-06-08 16:38:08', 'createUser': 139, 'currentUser': 862885, 'stationName': '充电桩模拟209370', 'workOrderLogs': [{'id': 6, 'workOrderId': 6, 'log': '工单创建', 'userId': 139, 'createTime': '2021-06-08 16:38:08', 'userName': 'admin'}]}}
DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': 0, 'data': {'id': 6, 'type': 1, 'stationId': 100208, 'details': '测试', 'status': 1, 'createTime': '2021-06-08 16:38:08', 'createUser': 139, 'currentUser': 862885, 'stationName': '充电桩模拟209370', 'workOrderLogs': [{'id': 6, 'workOrderId': 6, 'log': '工单创建', 'userId': 139, 'createTime': '2021-06-08 16:38:08', 'userName': 'admin'}]}}
WARNING  celery.redirected:log.py:227 [2021-06-10 15:31:14,861] | mylogger.py |DEBUG : 测试结果:get,,,{'errorCode': 0, 'data': {'id': 6, 'type': 1, 'stationId': 100208, 'details': '测试', 'status': 1, 'createTime': '2021-06-08 16:38:08', 'createUser': 139, 'currentUser': 862885, 'stationName': '充电桩模拟209370', 'workOrderLogs': [{'id': 6, 'workOrderId': 6, 'log': '工单创建', 'userId': 139, 'createTime': '2021-06-08 16:38:08', 'userName': 'admin'}]}}
WARNING  celery.redirected:log.py:227 get 请求结束。。。。。。