WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7fe5e41b6470>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': 'b05815be-1e2c-4f17-95cb-ffef633b9827', 'sid': 'KDp6dQcHfYz0'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': 'b05815be-1e2c-4f17-95cb-ffef633b9827', 'sid': 'KDp6dQcHfYz0'}}
WARNING  celery.redirected:log.py:227 [2021-06-04 19:14:22,688] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': 'b05815be-1e2c-4f17-95cb-ffef633b9827', 'sid': 'KDp6dQcHfYz0'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:b05815be-1e2c-4f17-95cb-ffef633b9827
DEBUG    root:mylogger.py:80 token:b05815be-1e2c-4f17-95cb-ffef633b9827
WARNING  celery.redirected:log.py:227 [2021-06-04 19:14:22,689] | mylogger.py |DEBUG : token:b05815be-1e2c-4f17-95cb-ffef633b9827
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:b05815be-1e2c-4f17-95cb-ffef633b9827
DEBUG    root:mylogger.py:80 token:b05815be-1e2c-4f17-95cb-ffef633b9827
WARNING  celery.redirected:log.py:227 [2021-06-04 19:14:22,691] | mylogger.py |DEBUG : token:b05815be-1e2c-4f17-95cb-ffef633b9827