WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7f9bcb539240>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '811ff5ff-35c1-4679-ae54-a3f94500085b'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '811ff5ff-35c1-4679-ae54-a3f94500085b'}}
WARNING  celery.redirected:log.py:227 [2021-06-01 16:21:16,955] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '811ff5ff-35c1-4679-ae54-a3f94500085b'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:811ff5ff-35c1-4679-ae54-a3f94500085b
DEBUG    root:mylogger.py:80 token:811ff5ff-35c1-4679-ae54-a3f94500085b
WARNING  celery.redirected:log.py:227 [2021-06-01 16:21:16,956] | mylogger.py |DEBUG : token:811ff5ff-35c1-4679-ae54-a3f94500085b
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:811ff5ff-35c1-4679-ae54-a3f94500085b
DEBUG    root:mylogger.py:80 token:811ff5ff-35c1-4679-ae54-a3f94500085b
WARNING  celery.redirected:log.py:227 [2021-06-01 16:21:16,957] | mylogger.py |DEBUG : token:811ff5ff-35c1-4679-ae54-a3f94500085b