WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7fb16ce18b70>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': 'e99218d7-5f1c-4826-a592-f6aea9b53fa6'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': 'e99218d7-5f1c-4826-a592-f6aea9b53fa6'}}
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,081] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': 'e99218d7-5f1c-4826-a592-f6aea9b53fa6'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:e99218d7-5f1c-4826-a592-f6aea9b53fa6
DEBUG    root:mylogger.py:80 token:e99218d7-5f1c-4826-a592-f6aea9b53fa6
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,082] | mylogger.py |DEBUG : token:e99218d7-5f1c-4826-a592-f6aea9b53fa6
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:e99218d7-5f1c-4826-a592-f6aea9b53fa6
DEBUG    root:mylogger.py:80 token:e99218d7-5f1c-4826-a592-f6aea9b53fa6
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,084] | mylogger.py |DEBUG : token:e99218d7-5f1c-4826-a592-f6aea9b53fa6