WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7f9bcb592d68>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '9437c3b2-f6a9-46d4-858b-7e90f439fb55', 'sid': 'ksfJ3peHffkD'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '9437c3b2-f6a9-46d4-858b-7e90f439fb55', 'sid': 'ksfJ3peHffkD'}}
WARNING  celery.redirected:log.py:227 [2021-06-01 20:04:20,754] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '9437c3b2-f6a9-46d4-858b-7e90f439fb55', 'sid': 'ksfJ3peHffkD'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:9437c3b2-f6a9-46d4-858b-7e90f439fb55
DEBUG    root:mylogger.py:80 token:9437c3b2-f6a9-46d4-858b-7e90f439fb55
WARNING  celery.redirected:log.py:227 [2021-06-01 20:04:20,755] | mylogger.py |DEBUG : token:9437c3b2-f6a9-46d4-858b-7e90f439fb55
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:9437c3b2-f6a9-46d4-858b-7e90f439fb55
DEBUG    root:mylogger.py:80 token:9437c3b2-f6a9-46d4-858b-7e90f439fb55
WARNING  celery.redirected:log.py:227 [2021-06-01 20:04:20,756] | mylogger.py |DEBUG : token:9437c3b2-f6a9-46d4-858b-7e90f439fb55