WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7fe5e43097b8>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '9b612de9-1c59-432f-be6c-fae601689d25', 'sid': '7ZmfE9wLgd30'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '9b612de9-1c59-432f-be6c-fae601689d25', 'sid': '7ZmfE9wLgd30'}}
WARNING  celery.redirected:log.py:227 [2021-06-04 17:42:21,659] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '9b612de9-1c59-432f-be6c-fae601689d25', 'sid': '7ZmfE9wLgd30'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:9b612de9-1c59-432f-be6c-fae601689d25
DEBUG    root:mylogger.py:80 token:9b612de9-1c59-432f-be6c-fae601689d25
WARNING  celery.redirected:log.py:227 [2021-06-04 17:42:21,660] | mylogger.py |DEBUG : token:9b612de9-1c59-432f-be6c-fae601689d25
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:9b612de9-1c59-432f-be6c-fae601689d25
DEBUG    root:mylogger.py:80 token:9b612de9-1c59-432f-be6c-fae601689d25
WARNING  celery.redirected:log.py:227 [2021-06-04 17:42:21,661] | mylogger.py |DEBUG : token:9b612de9-1c59-432f-be6c-fae601689d25