WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7fe5e41cd0f0>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/login HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '973f66a0-013f-4f7a-b358-c0071ae48961', 'sid': 'YhXBduoECTpi'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '973f66a0-013f-4f7a-b358-c0071ae48961', 'sid': 'YhXBduoECTpi'}}
WARNING  celery.redirected:log.py:227 [2021-06-04 19:04:11,073] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '973f66a0-013f-4f7a-b358-c0071ae48961', 'sid': 'YhXBduoECTpi'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:973f66a0-013f-4f7a-b358-c0071ae48961
DEBUG    root:mylogger.py:80 token:973f66a0-013f-4f7a-b358-c0071ae48961
WARNING  celery.redirected:log.py:227 [2021-06-04 19:04:11,074] | mylogger.py |DEBUG : token:973f66a0-013f-4f7a-b358-c0071ae48961
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:973f66a0-013f-4f7a-b358-c0071ae48961
DEBUG    root:mylogger.py:80 token:973f66a0-013f-4f7a-b358-c0071ae48961
WARNING  celery.redirected:log.py:227 [2021-06-04 19:04:11,076] | mylogger.py |DEBUG : token:973f66a0-013f-4f7a-b358-c0071ae48961