WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:基础信息
INFO     root:mylogger.py:78 case用例:基础信息
WARNING  celery.redirected:log.py:227 [2021-06-08 08:58:40,754] | mylogger.py |INFO  : case用例:基础信息
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/myInfo
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/myInfo
WARNING  celery.redirected:log.py:227 [2021-06-08 08:58:40,755] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/myInfo
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：ab134be7-f890-42e3-9137-7e23f1432ff1
INFO     root:mylogger.py:78 token：ab134be7-f890-42e3-9137-7e23f1432ff1
WARNING  celery.redirected:log.py:227 [2021-06-08 08:58:40,756] | mylogger.py |INFO  : token：ab134be7-f890-42e3-9137-7e23f1432ff1
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer ab134be7-f890-42e3-9137-7e23f1432ff1', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-06-08 08:58:40,757] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/myInfo HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/myInfo HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-06-08 08:58:41,043] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。