WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:站点设备信息统计
INFO     root:mylogger.py:78 case用例:站点设备信息统计
WARNING  celery.redirected:log.py:227 [2021-05-31 20:01:13,834] | mylogger.py |INFO  : case用例:站点设备信息统计
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/station/partnerDeviceInfo
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/station/partnerDeviceInfo
WARNING  celery.redirected:log.py:227 [2021-05-31 20:01:13,835] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/station/partnerDeviceInfo
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：e9ad6d42-d752-4c09-b9e8-5a343855edbe
INFO     root:mylogger.py:78 token：e9ad6d42-d752-4c09-b9e8-5a343855edbe
WARNING  celery.redirected:log.py:227 [2021-05-31 20:01:13,835] | mylogger.py |INFO  : token：e9ad6d42-d752-4c09-b9e8-5a343855edbe
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer e9ad6d42-d752-4c09-b9e8-5a343855edbe', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-05-31 20:01:13,837] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/station/partnerDeviceInfo HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/station/partnerDeviceInfo HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-05-31 20:01:14,006] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。