WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:合作伙伴基本信息
INFO     root:mylogger.py:78 case用例:合作伙伴基本信息
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,534] | mylogger.py |INFO  : case用例:合作伙伴基本信息
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/partnerInfo
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/partnerInfo
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,535] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/partnerInfo
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：e99218d7-5f1c-4826-a592-f6aea9b53fa6
INFO     root:mylogger.py:78 token：e99218d7-5f1c-4826-a592-f6aea9b53fa6
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,536] | mylogger.py |INFO  : token：e99218d7-5f1c-4826-a592-f6aea9b53fa6
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer e99218d7-5f1c-4826-a592-f6aea9b53fa6', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,537] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/partnerInfo HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/partnerInfo HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-05-31 19:02:49,736] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。