WARNING  celery.redirected:log.py:227 token
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6', 'sid': 'QVHpTXqX4mfK'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6', 'sid': 'QVHpTXqX4mfK'}}
WARNING  celery.redirected:log.py:227 [2021-05-24 18:04:48,570] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6', 'sid': 'QVHpTXqX4mfK'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6
DEBUG    root:mylogger.py:80 token:9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6
WARNING  celery.redirected:log.py:227 [2021-05-24 18:04:48,572] | mylogger.py |DEBUG : token:9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6
DEBUG    root:mylogger.py:80 token:9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6
WARNING  celery.redirected:log.py:227 [2021-05-24 18:04:48,576] | mylogger.py |DEBUG : token:9048b009-8a2c-4c2b-bb4f-bd2992f3a6b6