WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:14客诉工单 详情
INFO     root:mylogger.py:78 case用例:14客诉工单 详情
WARNING  celery.redirected:log.py:227 [2021-06-08 15:41:10,334] | mylogger.py |INFO  : case用例:14客诉工单 详情
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderDetails
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderDetails
WARNING  celery.redirected:log.py:227 [2021-06-08 15:41:10,335] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/workOrderDetails
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：e3b07e69-08ca-4b83-a502-7e7296e536b3
INFO     root:mylogger.py:78 token：e3b07e69-08ca-4b83-a502-7e7296e536b3
WARNING  celery.redirected:log.py:227 [2021-06-08 15:41:10,336] | mylogger.py |INFO  : token：e3b07e69-08ca-4b83-a502-7e7296e536b3
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer e3b07e69-08ca-4b83-a502-7e7296e536b3', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :get
WARNING  celery.redirected:log.py:227 pararm :{"id":6}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 get 请求 ....
DEBUG    root:mylogger.py:80 get 请求 ....
WARNING  celery.redirected:log.py:227 [2021-06-08 15:41:10,337] | mylogger.py |DEBUG : get 请求 ....
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderDetails?id=6 HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderDetails?id=6 HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': -7, 'msg': '8db6cd-/bp/workOrderDetails出错了，请联系客服'}
DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': -7, 'msg': '8db6cd-/bp/workOrderDetails出错了，请联系客服'}
WARNING  celery.redirected:log.py:227 [2021-06-08 15:41:10,462] | mylogger.py |DEBUG : 测试结果:get,,,{'errorCode': -7, 'msg': '8db6cd-/bp/workOrderDetails出错了，请联系客服'}